language: python
python:
- 3.6
- 3.5
- 3.4
- 2.7
# install: pip install -U tox-travis
# script: tox
install: pip install -e .
script: pip install -e .
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: ashutoshdtu
  password:
    secure: oezm9vjEVtC/jHM2zg38jhCZ7Ue2ghBBqDMc4RNwT9k5AINKklJ9pmOT03pJ2+czz3sSQnlbfwEJttTlRKV/J469rO82MPGi0YSfdcQltrn6zDfKo6ZVQy+dWBIli52GvMKrQZri1CUS+FUxzD2AyLNdsGIU6tsciQOvUYANIkVcZ+1DK2L0XUYAIr6t6gRmhmkyXjW2p4ewDZK2I92c/bc+0Gq1jAPOQfu0uDQk03HTDAbWKRIJoqKJSpQFpnvZZLuBaRm8eHVwGrvfBumyTOXGaUgTtTnKk/sN7IJSjoYMezCJ4vKLi0D6lc3fpsmzIMULGzOvXiWdBCPoLpwzZxhEkRWy4H4iFeClrSySHrTWck2o2qNYW1xFIhgT9wJ+Ghz8a5ussFJrDhhwsbio85YMdJH5T/hn1gv0cNwHC/G9Gls9pAFFp6GecJt/eu14XRbQubpNvnP05TcWuH3K052DScJ9RetuA/2hekIGGuAYPN0rrFYGWCV2sBPKxTqp8COVYatkAo6OttdKZo1p4mdC9qSaULVLuQDjhWsP0ba/5wC1LEd0mGhy5qjXJA7H3/AN3VQfHmQ3xeF1Hzhwmcs5E/RCETxGCpfKDPSkcuZYLt66FhTtkAiBI9Zu6Pghc46xg0hWW/4G8c0bMg9SmYz9ZkKBHKpeN1rqUI2fZvg=
  on:
    tags: true
    repo: ashutoshdtu/eazyserver
    python: 3.6
